name = "hexxytest3"
author = "chloe"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ac2d7cce66f854a75485654af29f7d613a558f70c8dff6c477e871fd922e5a8e"

[versions]
fabric = "0.16.14"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["1.20"]
