name = "hexxytest3"
author = "chloe"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3a8b12a1c2e63f0bff4fd334cb3e2bb9fd24369c52a8b85117f49fa2c70a3b4c"

[versions]
fabric = "0.16.14"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["1.20"]
